name: Keep Sync with Source
run-name: Keeping sync with branch source.
on:
  push:
  workflow_dispatch:
jobs:
  Merge:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repository
        uses: actions/checkout@v4
      - name: set up git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Merge the branches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch
          git branch -v
          git checkout ubuntu
          git merge origin/source
          git add .
          git commit -m "auto merge"
          git push
          git checkout Mac
          git merge origin/source
          git add .
          git commit -m "auto merge"
          git push
      - run: echo "job status is ${{ job.status }}"
      
