name: Keep Sync with Source
run-name: Keeping sync with branch source.
on:
  push:
    branches:
      - source
  workflow_dispatch:
jobs:
  Merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge the branches
        run: |
          git clone https://github.com/Wangzehao2009/duipai_ji.git
          cd duipai_ji
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          git checkout -b source
          git checkout -b ubuntu
          git merge source
          git add .
          git commit -m "sync"
          git push
          git checkout -b Mac
          git merge source
          git add .
          git commit -m "sync"
          git push
      - run: echo "job status is ${{ job.status }}"
      
